# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nishimi-ya/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bluesky"
name = "Bluesky"
url = "https://bsky.nishimiya.my.id"

[social.params]
icon = "brand-bluesky"

[[social]]
identifier = "linktree"
name = "Linktree"
url = "https://linktr.ee/nishi.miya"

[social.params]
icon = "brand-linktree"

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://www.youtube.com/@nishimiya6540"

[social.params]
icon = "brand-youtube"
